#!/usr/bin/env python3
## made by Chris Chauvot (Az8th)

from sys import argv, exit
from PIL import Image

def readImage(filename):
    sizeX = 0
    sizeY = 0
    color = (0, 0, 0)
    nextColor = False
    with open(filename) as source:
        for line in source:
            line = line[:-1]
            if (line) == '--':
                nextColor = True
            elif (line) == '-':
                pass
            elif nextColor == True:
                nextColor = False
                line = line[1:-1].split(",")
                color = (int(float(line[0])), int(float(line[1])), int(float(line[2])))
            else:
                line = line[1:line.find(") (", 4)].split(",")
                x = int(line[0])
                y = int(line[1])
                sizeX = max(sizeX, x)
                sizeY = max(sizeY, y)
                pixels[(x, y)] = color
    return (sizeX, sizeY)

def writeImage(filename, size):
    for x in range(size[0]):
        for y in range(size[1]):
            if (x, y) not in pixels:
                print("ERROR: Pixel (" + str(x) + ", " + str(y) + ") is missing") 
                exit(84)
            img.putpixel((x, y), pixels[x, y])
    img.save(filename)

if (len(argv) != 3):
    exit(84)
compressRatio = 0.5
pixels = {}
size = readImage(argv[1])
img = Image.new("RGB", (size[0], size[1]))
writeImage(argv[2], size)
